export const LOAD_HISTORY = "LOAD_HISTORY";
export const LOAD_HISTORY_SUCCESS = "LOAD_HISTORY_SUCCESS";
export const LOAD_HISTORY_FAIL = "LOAD_HISTORY_FAIL";

export const UPLOAD_SETTINGS = "UPLOAD_SETTINGS";
export const UPLOAD_SETTINGS_SUCCESS = "UPLOAD_SETTINGS_SUCCESS";
export const UPLOAD_SETTINGS_FAIL = "UPLOAD_SETTINGS_FAIL";